# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dob',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.SlugField(max_length=25),
        ),
        migrations.AlterField(
            model_name='book',
            name='prologue',
            field=models.TextField(max_length=500),
        ),
    ]
