# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0003_auto_20180104_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='male',
            field=models.BooleanField(default=True),
        ),
    ]
